// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKLVQ_XBPrCZpP2DwSlbCIGi7xwPR-Mqw',
    appId: '1:649326221728:android:cc1c3e715e453ef1caacc5',
    messagingSenderId: '649326221728',
    projectId: 'kwart-ai-8f93e',
    storageBucket: 'kwart-ai-8f93e.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8N6URdD_GNxeBBVjVmFSy768YKun5gHY',
    appId: '1:649326221728:web:a276cf27edf8b069caacc5',
    messagingSenderId: '649326221728',
    projectId: 'kwart-ai-8f93e',
    authDomain: 'kwart-ai-8f93e.firebaseapp.com',
    storageBucket: 'kwart-ai-8f93e.firebasestorage.app',
    measurementId: 'G-BLBE63EQKL',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8N6URdD_GNxeBBVjVmFSy768YKun5gHY',
    appId: '1:649326221728:web:d91b03806c1a06a6caacc5',
    messagingSenderId: '649326221728',
    projectId: 'kwart-ai-8f93e',
    authDomain: 'kwart-ai-8f93e.firebaseapp.com',
    storageBucket: 'kwart-ai-8f93e.firebasestorage.app',
    measurementId: 'G-X3HG2N4H1Z',
  );
}
